name: MacOS

on:
  push:
    branches:  [ main ]
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [ 'tebako release' ]

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  test-sinatra:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14 ]
    steps:
      - name: Select XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.0.1

      - name: Brew install
        run: |
          brew install bison flex binutils libffi double-conversion boost jemalloc fmt glog gnu-sed bash zlib ncurses
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH

      - name: Install gem
        run: gem install tebako

      - name: Checkout sample
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bundle install

      - name: Package
        run: |
          tebako press \
            --root=./ \
            --entry-point=trmnl-liquid-cli.rb \
            --output=liquid-cli \
            --Ruby=3.3.7

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: liquid-cli-macos-14
          path: liquid-cli
          if-no-files-found: error
          retention-days: 14